version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ws
      - HTTP_PROXY=http://mitmproxy:8080
      - HTTPS_PROXY=http://mitmproxy:8080
    depends_on:
      - db
      - mitmproxy
    networks:
      - app-network
    volumes:
      # Mount for the mitmproxy certificate
      - ./mitmproxy-ca-cert:/usr/local/share/ca-certificates/mitmproxy

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    ports:
      - "8080:8080"
      - "8081:8081"
    command: mitmweb --web-host 0.0.0.0
    networks:
      - app-network
    volumes:
      # Persist mitmproxy data for the CA certificate
      - ./mitmproxy-data:/home/mitmproxy/.mitmproxy

volumes:
  postgres-data:
  mitmproxy-data:

networks:
  app-network:
    driver: bridge
